### ISSUE TITLE
Errors on 1.21.1

### ISSUE THREAD

**Issue by CityPvP** [wilozyx/Classic-Mechanics#5]
[02:58:52 WARN]: Found loot table element validation problem in {minecraft:loot_table/minecraft:gameplay/fishing}.pools[2].entries[1]->{minecraft:gameplay/fishing/treasure_2}.pools[0].entries[2]: Unreachable entry!
[02:58:52 WARN]: Found loot table element validation problem in {minecraft:loot_table/minecraft:gameplay/fishing/treasure_2}.pools[0].entries[2]: Unreachable entry!
[02:58:52 ERROR]: Couldn't read tag list classic_mechanics:old_tool_breakables/diamond_tools/diamond_pickaxe from classic_mechanics:tags/item/old_tool_breakables/diamond_tools/diamond_pickaxe.json in data pack file/Classic Mechanics v1.12.1
java.lang.IllegalStateException: Not a JSON object: [{"function":"minecraft:set_components","components":{"minecraft:tool":{"rules":[{"blocks":"#minecraft:incorrect_for_diamond_tool","correct_for_drops":false},{"blocks":"#classic_mechanics:mineable/pickaxe/pickaxe","speed":8,"correct_for_drops":true},{"blocks":"#classic_mechanics:mineable/pickaxe/1_metal_blocks","speed":5,"correct_for_drops":true},{"blocks":"#classic_mechanics:mineable/pickaxe/2_rock_blocks","speed":2,"correct_for_drops":true},{"blocks":"#classic_mechanics:mineable/pickaxe/3_hard_blocks","speed":1.5,"correct_for_drops":true}]}}}]
        at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
        at net.minecraft.tags.TagLoader.load(TagLoader.java:53) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
        at net.minecraft.tags.TagLoader.loadAndBuild(TagLoader.java:118) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
        at net.minecraft.tags.TagManager.lambda$createLoader$3(TagManager.java:58) ~[paper-1.21.1.jar:1.21.1-96-4514c71]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by wilozyx** [comment]
Just wanted to add a comment here since I read and fixed this bug 2 weeks ago, and it'll come with the build for the next version (v1.13.0) of Classic Mechanics, although I am delaying it a bit since I have been working a lot on other projects aswell. But do know that this is fixed next update 👍
